import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import { LocalesContext } from '../locales/LocalesContext';
import { ApolloClientContext } from '../contexts/ApolloClientContext';
import { ReactNode } from 'react';
import localFont from 'next/font/local';
import { Navigation } from '../components/Navigation';
import { Footer } from '../components/Footer';

const ourFont = localFont({ src: '../fonts/eurostarregularextended.ttf' });
export const metadata: Metadata = {
	title: 'Andalusia Home',
	description: 'Generated by create next app',
};

export default function AppLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang={'en'}>
			<body className={ourFont.className} style={{ minHeight: '100vh' }}>
				<ApolloClientContext>
					<AppRouterCacheProvider>
						<ThemeProvider theme={theme}>
							<LocalesContext>
								<Navigation />
								{children}
								<Footer />
							</LocalesContext>
						</ThemeProvider>
					</AppRouterCacheProvider>
				</ApolloClientContext>
			</body>
		</html>
	);
}
