version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/frontend2'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/apigw'
    schedule:
      interval: 'weekly'
