import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import { LocalesContext } from '../locales/LocalesContext';
import { ApolloClientContext } from '../contexts/ApolloClientContext';
import { ReactNode } from 'react';
import localFont from 'next/font/local';
import { Navigation } from '../components/Navigation';
import { Footer } from '../components/Footer';
import { FiltersProvider } from '../contexts/FiltersContext';

const ourFont = localFont({ src: '../fonts/eurostarregularextended.ttf' });

export const metadata: Metadata = {
	title: 'Andalusia Home',
	description: 'Generated by create next app',
};

export default function AppLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	if (process.env.REACT_APP_COMMIT_HASH != null) {
		console.log(`Commit hash %c${process.env.REACT_APP_COMMIT_HASH}`, 'font-weight: bold');
	}

	if (process.env.REACT_APP_BUILT_AT != null) {
		console.log(`Build at %c${process.env.REACT_APP_BUILT_AT}`, 'font-weight: bold');
	}
	return (
		<html lang={'en'}>
			<head>
				<meta name={'viewport'} content={'width=device-width initial-scale=1 viewport-fit=cover'} />
				<meta name={'mobile-web-app-capable'} content={'yes'} />
				<meta name={'apple-mobile-web-app-capable'} content={'yes'} />
				<meta name={'theme-color'} content={'#000'} />
			</head>
			<body className={ourFont.className} style={{ minHeight: '100vh' }}>
				<ApolloClientContext>
					<AppRouterCacheProvider>
						<ThemeProvider theme={theme}>
							<LocalesContext>
								<FiltersProvider>
									<Navigation />
									{children}
									<Footer />
								</FiltersProvider>
							</LocalesContext>
						</ThemeProvider>
					</AppRouterCacheProvider>
				</ApolloClientContext>
			</body>
		</html>
	);
}
