import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { IntlProvider, FormattedMessage, FormattedNumber } from 'react-intl';
import { LocalesContext } from '../../locales/LocalesContext';
import { ApolloClientContext } from '../../contexts/ApolloClientContext';
import { ReactNode } from 'react';
import Header from 'components/header/Header';
import Footer from 'components/footer/Footer';
import Navbar from 'components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Andalusia Home',
	description: 'Generated by create next app',
};

export default function AppLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang={'en'}>
			<body className={inter.className}>
				<ApolloClientContext>
					<LocalesContext>
						<Navbar />
						{children}
						<Footer />
					</LocalesContext>
				</ApolloClientContext>
			</body>
		</html>
	);
}
