import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { LocalesContext } from '../../locales/LocalesContext';
import { ApolloClientContext } from '../../contexts/ApolloClientContext';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Andalusia Home',
	description: 'Generated by create next app',
};

export default function AppLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang={'en'}>
			<body className={inter.className} style={{ minHeight: '100vh' }}>
				<ApolloClientContext>
					<LocalesContext>{children}</LocalesContext>
				</ApolloClientContext>
			</body>
		</html>
	);
}
