name: APIGW Build & Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build APIGW
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn apigw:build

      - name: Check build success
        if: ${{ success() }}
        run: |
          echo "Build failed!"
          exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Render
        env:
          APIGW_DEPLOY_APIKEY: ${{ secrets.APIGW_DEPLOY_APIKEY }}
          APIGW_DEPLOY_SERVICE_ID: ${{ secrets.APIGW_DEPLOY_SERVICE_ID }}
          APIGW_DEPLOY_HOOK_SECRET: ${{ secrets.APIGW_DEPLOY_HOOK_SECRET }}
        run: |
          echo "Deploying APIGW to Render"
          curl -X POST https://api.render.com/deploy/srv-$APIGW_DEPLOY_SERVICE_ID?key=$APIGW_DEPLOY_HOOK_SECRET
