name: Build and Deploy API Gateway

on:
  push:
    paths:
      - 'apigw/**'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clean node_modules
        run: rm -rf ${{ github.workspace }}/apigw/node_modules || true

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/apigw
        run: yarn install || echo "Failed to install dependencies"

  build:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: List current directory contents before build
        run: ls -la ${{ github.workspace }}

      - name: List apigw directory contents before build
        run: ls -la ${{ github.workspace }}/apigw || echo "apigw directory not found"

      - name: Build application
        working-directory: ${{ github.workspace }}
        run: yarn apigw:build || echo "Build failed"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy to Render
        env:
          APIGW_DEPLOY_APIKEY: ${{ secrets.APIGW_DEPLOY_APIKEY }}
          APIGW_DEPLOY_SERVICE_ID: ${{ secrets.APIGW_DEPLOY_SERVICE_ID }}
          APIGW_DEPLOY_HOOK_SECRET: ${{ secrets.APIGW_DEPLOY_HOOK_SECRET }}
        run: |
          echo "Deploying APIGW to Render"
          curl -X POST https://api.render.com/deploy/srv-$APIGW_DEPLOY_SERVICE_ID?key=$APIGW_DEPLOY_HOOK_SECRET
