name: Deploy Dev
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      
    - name: Get the commit hash
      run: echo "REACT_APP_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Get the build time
      run: echo "REACT_APP_BUILT_AT=$(date +%Y-%m-%dT%H:%M:%S)" >> $GITHUB_ENV

    - run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/prj_QwAIbk2SSOaNDkxh9Y3jTWX1OZQm/jrNSnozLDW
