name: Deploy to Netlify

on:
  push:
    tags:
      - '*' # Spouští workflow při pushi jakéhokoli tagu

jobs:
  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn workspace frontend build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Trigger Netlify Deployment
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/66c90892d1cee323af153272
        env:
          DEPLOY_FRONTEND_WEBHOOK: ${{ secrets.DEPLOY_FRONTEND_WEBHOOK }}

    
